//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neat.Procedure.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DBScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neat.Procedure.Tests.DBScripts", typeof(DBScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ExecuteScalarWithReturnValueAsInt]
        ///AS
        ///BEGIN
        ///	RETURN 42
        ///END
        ///GO
        ///CREATE PROCEDURE [ExecuteScalarWithSelectAsInt]
        ///AS
        ///BEGIN
        ///	SELECT 42
        ///END
        ///GO
        ///CREATE PROCEDURE [ExecuteScalarWithSelectAsVarChar]
        ///AS
        ///BEGIN
        ///	SELECT &apos;The answer is 42&apos;
        ///END
        ///GO
        ///CREATE PROCEDURE [ExecuteScalarWithSelectAsDateTime]
        ///AS
        ///BEGIN
        ///	SELECT CONVERT(DATETIME, &apos;2012-01-01&apos;)
        ///END
        ///GO
        ///CREATE PROCEDURE [ExecuteScalarWithSelectAsBooleanTrue]
        ///AS
        ///BEGIN
        ///	SELECT CONVERT(BIT, 1)
        ///END
        ///GO
        ///CREATE PROCEDURE [ExecuteSc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateAllProcedures {
            get {
                return ResourceManager.GetString("CreateAllProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE DATABASE [NeatProcedureDBTest] ON  PRIMARY 
        ///    ( NAME = N&apos;NeatProcedureDBTest&apos;, FILENAME = N&apos;C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\NeatProcedureDBTest.mdf&apos;, MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
        ///     LOG ON 
        ///    ( NAME = N&apos;NeatProcedureDBTest_log&apos;, FILENAME = N&apos;C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\NeatProcedureDBTest_log.ldf&apos;, MAXSIZE = UNLIMITED, FILEGROWTH = 10%).
        /// </summary>
        internal static string CreateDataBase {
            get {
                return ResourceManager.GetString("CreateDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER DATABASE [NeatProcedureDBTest] 
        ///    SET SINGLE_USER 
        ///    WITH ROLLBACK IMMEDIATE
        ///DROP DATABASE [NeatProcedureDBTest].
        /// </summary>
        internal static string DropDataBase {
            get {
                return ResourceManager.GetString("DropDataBase", resourceCulture);
            }
        }
    }
}
